apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypythonapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypythonapp-deploy
  template:
    metadata:
      labels:
        app: mypythonapp-deploy
    spec:
      containers:
        - name: myapp
          image: tameemdevops/myapp:dummy
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mypythonapp-svc
spec:
  selector:
    app: mypythonapp-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mypythonapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: mypythonapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mypythonapp-svc
                port:
                  number: 80
